version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kapsulkeasliandb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - kapsulkeaslian_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "timezone=Asia/Jakarta"]

volumes:
  kapsulkeaslian_data:
